### ISSUE TITLE
Could not pass event PlayerDeathEvent to MinecraftManhunt v1.3.1

### ISSUE THREAD

**Issue by nordowl** [Matistan/MinecraftManhunt#2]
At the end of a manhunt session I noticed some errors in the logs.
Everytime the hunter died, there was a `Could not pass event PlayerDeathEvent to MinecraftManhunt v1.3.1` error.

Logs below or [here (color coded)](https://mclo.gs/FNonFsC)
```bash
[17:47:15] [Server thread/INFO]: Golden_Armada has made the advancement [Acquire Hardware]
[17:47:17] [Server thread/INFO]: Golden_Armada has made the advancement [Diamonds!]
[17:48:09] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to MinecraftManhunt v1.3.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:928) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:828) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1524) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:938) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:983) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1275) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2031) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2380) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(SourceFile:166) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2305) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:33) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "org.bukkit.inventory.meta.ItemMeta.getLore()" is null
	at me.matistan05.minecraftmanhunt.listeners.DeathListener.DeathEvent(DeathListener.java:26) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 30 more
[17:48:09] [Server thread/INFO]: FluxiumYT was slain by Golden_Armada
[17:48:09] [Server thread/INFO]: Golden_Armada has made the advancement [Isn't It Iron Pick]
[17:48:09] [Server thread/INFO]: Golden_Armada has made the advancement [Stone Age]
[17:48:09] [Server thread/INFO]: Golden_Armada has made the advancement [Suit Up]
[17:50:06] [Server thread/INFO]: FluxiumYT has made the advancement [Getting an Upgrade]
[17:54:10] [Server thread/INFO]: FluxiumYT has made the advancement [Hot Stuff]
[17:55:01] [Server thread/INFO]: Golden_Armada has made the advancement [Monster Hunter]
[17:56:25] [Server thread/INFO]: FluxiumYT has made the advancement [Monster Hunter]
[17:56:33] [Server thread/INFO]: Golden_Armada has made the advancement [Hot Stuff]
[17:58:03] [Server thread/INFO]: FluxiumYT issued server command: /manhunt pause
[17:58:14] [Server thread/INFO]: Golden_Armada issued server command: /manhunt pause
[17:58:42] [Server thread/INFO]: FluxiumYT issued server command: /manhunt resume
[17:58:46] [Server thread/INFO]: FluxiumYT issued server command: /manhunt unpause
[17:58:52] [Server thread/INFO]: Golden_Armada issued server command: /manhunt unpause
[18:04:48] [Server thread/INFO]: Golden_Armada issued server command: /manhunt pause
[18:04:50] [Server thread/INFO]: FluxiumYT issued server command: /manhunt pause
[18:05:09] [Server thread/INFO]: Golden_Armada issued server command: /manhunt unpause
[18:05:09] [Server thread/INFO]: FluxiumYT issued server command: /manhunt unpause
[18:16:05] [Server thread/INFO]: FluxiumYT has made the advancement [Sweet Dreams]
[18:16:31] [Server thread/INFO]: Villager EntityVillager['Cartographer'/22356, l='ServerLevel[survival_2024]', x=-480.92, y=64.00, z=-1548.35] died, message: 'Cartographer was slain by Husk'
[18:18:03] [Server thread/INFO]: FluxiumYT has made the advancement [Not Today, Thank You]
[18:20:17] [Server thread/INFO]: Golden_Armada issued server command: /manhunt pause
[18:20:19] [Server thread/INFO]: FluxiumYT issued server command: /manhunt pause
[18:20:27] [Server thread/INFO]: FluxiumYT issued server command: /manhunt unpause
[18:20:29] [Server thread/INFO]: Golden_Armada issued server command: /manhunt unpause
[18:22:46] [Server thread/INFO]: Golden_Armada has made the advancement [We Need to Go Deeper]
[18:24:55] [Server thread/INFO]: FluxiumYT has made the advancement [We Need to Go Deeper]
[18:25:08] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to MinecraftManhunt v1.3.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:928) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:828) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1524) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:938) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:983) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.Entity.as(Entity.java:630) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.EntityLiving.as(EntityLiving.java:406) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.Entity.l(Entity.java:584) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.EntityLiving.l(EntityLiving.java:2893) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.player.EntityHuman.l(EntityHuman.java:268) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.m(EntityPlayer.java:670) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.network.PlayerConnection.e(PlayerConnection.java:336) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.NetworkManager.d(NetworkManager.java:392) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:180) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:387) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1242) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "org.bukkit.inventory.meta.ItemMeta.getLore()" is null
	at me.matistan05.minecraftmanhunt.listeners.DeathListener.DeathEvent(DeathListener.java:26) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 23 more
[18:25:08] [Server thread/INFO]: FluxiumYT burned to death
[18:25:46] [Server thread/INFO]: FluxiumYT was burned to a crisp while fighting Golden_Armada
[18:26:04] [Server thread/INFO]: FluxiumYT was slain by Golden_Armada
[18:26:20] [Server thread/INFO]: FluxiumYT has made the advancement [Diamonds!]
[18:26:57] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to MinecraftManhunt v1.3.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:928) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:828) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1524) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:938) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:983) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1275) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2031) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2380) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(SourceFile:166) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:66) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2305) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:53) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:33) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4077-Spigot-e9ec548-dfaa89b]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "org.bukkit.inventory.meta.ItemMeta.getLore()" is null
	at me.matistan05.minecraftmanhunt.listeners.DeathListener.DeathEvent(DeathListener.java:26) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 30 more
[18:26:57] [Server thread/INFO]: FluxiumYT was slain by Golden_Armada
```

**Comment by Matistan** [comment]
Thanks for your feedback, I will fix this bug right away.

**Comment by Matistan** [comment]
This bug has been fixed in the newest update, so I'm closing the issue.
